# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface/puzzlebox_jigsaw_interface_design-plugin_orbit.ui'
#
# Created: Sat Jan 17 05:34:28 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
	def setupUi(self, Form):
		Form.setObjectName("Form")
#Form.resize()
		#self.horizontalLayoutWidget = QtGui.QWidget(Form)
		self.horizontalLayoutWidget = QtGui.QWidget()
		self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1719, 857))
		self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
		self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem)
		self.webViewOrbit = QtWebKit.QWebView(self.horizontalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.webViewOrbit.sizePolicy().hasHeightForWidth())
		self.webViewOrbit.setSizePolicy(sizePolicy)
		self.webViewOrbit.setObjectName("webViewOrbit")
		self.horizontalLayout.addWidget(self.webViewOrbit)
		spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem1)
		self.verticalLayout_4 = QtGui.QVBoxLayout()
		self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.horizontalLayout_4 = QtGui.QHBoxLayout()
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_4.addItem(spacerItem2)
		self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget)
		self.label_4.setObjectName("label_4")
		self.horizontalLayout_4.addWidget(self.label_4)
		spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_4.addItem(spacerItem3)
		self.verticalLayout_4.addLayout(self.horizontalLayout_4)
		self.widgetPlotRawEEG = QtGui.QWidget(self.horizontalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.widgetPlotRawEEG.sizePolicy().hasHeightForWidth())
		self.widgetPlotRawEEG.setSizePolicy(sizePolicy)
		self.widgetPlotRawEEG.setMinimumSize(QtCore.QSize(520, 160))
		self.widgetPlotRawEEG.setObjectName("widgetPlotRawEEG")
		self.labelMockupRawEEG = QtGui.QLabel(self.widgetPlotRawEEG)
		self.labelMockupRawEEG.setGeometry(QtCore.QRect(0, 0, 520, 160))
		self.labelMockupRawEEG.setText("")
		self.labelMockupRawEEG.setPixmap(QtGui.QPixmap("images/mockup-raw_eeg_waves.png"))
		self.labelMockupRawEEG.setObjectName("labelMockupRawEEG")
		self.verticalLayout_4.addWidget(self.widgetPlotRawEEG)
		self.horizontalLayoutOrbitControl = QtGui.QHBoxLayout()
		self.horizontalLayoutOrbitControl.setObjectName("horizontalLayoutOrbitControl")
		spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutOrbitControl.addItem(spacerItem4)
		self.labelOrbitControl = QtGui.QLabel(self.horizontalLayoutWidget)
		self.labelOrbitControl.setObjectName("labelOrbitControl")
		self.horizontalLayoutOrbitControl.addWidget(self.labelOrbitControl)
		spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutOrbitControl.addItem(spacerItem5)
		self.verticalLayout_4.addLayout(self.horizontalLayoutOrbitControl)
		self.horizontalLayoutFlightPlan = QtGui.QHBoxLayout()
		self.horizontalLayoutFlightPlan.setObjectName("horizontalLayoutFlightPlan")
		self.verticalLayoutFlightPlan = QtGui.QVBoxLayout()
		self.verticalLayoutFlightPlan.setObjectName("verticalLayoutFlightPlan")
		self.gridLayoutFlightPlan = QtGui.QGridLayout()
		self.gridLayoutFlightPlan.setObjectName("gridLayoutFlightPlan")
		self.labelHelicopterLand = QtGui.QLabel(self.horizontalLayoutWidget)
		self.labelHelicopterLand.setMidLineWidth(0)
		self.labelHelicopterLand.setTextFormat(QtCore.Qt.AutoText)
		self.labelHelicopterLand.setAlignment(QtCore.Qt.AlignCenter)
		self.labelHelicopterLand.setObjectName("labelHelicopterLand")
		self.gridLayoutFlightPlan.addWidget(self.labelHelicopterLand, 0, 2, 1, 1)
		self.labelHelicopterHover = QtGui.QLabel(self.horizontalLayoutWidget)
		self.labelHelicopterHover.setMidLineWidth(0)
		self.labelHelicopterHover.setTextFormat(QtCore.Qt.AutoText)
		self.labelHelicopterHover.setAlignment(QtCore.Qt.AlignCenter)
		self.labelHelicopterHover.setObjectName("labelHelicopterHover")
		self.gridLayoutFlightPlan.addWidget(self.labelHelicopterHover, 0, 0, 1, 1)
		self.labelHelicopterFlyForward = QtGui.QLabel(self.horizontalLayoutWidget)
		self.labelHelicopterFlyForward.setMidLineWidth(0)
		self.labelHelicopterFlyForward.setTextFormat(QtCore.Qt.AutoText)
		self.labelHelicopterFlyForward.setAlignment(QtCore.Qt.AlignCenter)
		self.labelHelicopterFlyForward.setObjectName("labelHelicopterFlyForward")
		self.gridLayoutFlightPlan.addWidget(self.labelHelicopterFlyForward, 0, 1, 1, 1)
		self.pushButtonHelicopterHover = QtGui.QPushButton(self.horizontalLayoutWidget)
		self.pushButtonHelicopterHover.setEnabled(True)
		self.pushButtonHelicopterHover.setMinimumSize(QtCore.QSize(0, 0))
		self.pushButtonHelicopterHover.setMaximumSize(QtCore.QSize(64, 64))
		self.pushButtonHelicopterHover.setText("")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("images/orbit-hover.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.pushButtonHelicopterHover.setIcon(icon)
		self.pushButtonHelicopterHover.setIconSize(QtCore.QSize(40, 40))
		self.pushButtonHelicopterHover.setCheckable(True)
		self.pushButtonHelicopterHover.setChecked(True)
		self.pushButtonHelicopterHover.setObjectName("pushButtonHelicopterHover")
		self.gridLayoutFlightPlan.addWidget(self.pushButtonHelicopterHover, 2, 0, 1, 1)
		self.pushButtonHelicopterSpinLeft = QtGui.QPushButton(self.horizontalLayoutWidget)
		self.pushButtonHelicopterSpinLeft.setEnabled(True)
		self.pushButtonHelicopterSpinLeft.setMinimumSize(QtCore.QSize(0, 0))
		self.pushButtonHelicopterSpinLeft.setMaximumSize(QtCore.QSize(64, 64))
		self.pushButtonHelicopterSpinLeft.setText("")
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap("images/orbit-rudder-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.pushButtonHelicopterSpinLeft.setIcon(icon1)
		self.pushButtonHelicopterSpinLeft.setIconSize(QtCore.QSize(40, 40))
		self.pushButtonHelicopterSpinLeft.setCheckable(True)
		self.pushButtonHelicopterSpinLeft.setChecked(False)
		self.pushButtonHelicopterSpinLeft.setObjectName("pushButtonHelicopterSpinLeft")
		self.gridLayoutFlightPlan.addWidget(self.pushButtonHelicopterSpinLeft, 4, 0, 1, 1)
		self.pushButtonHelicopterForward = QtGui.QPushButton(self.horizontalLayoutWidget)
		self.pushButtonHelicopterForward.setEnabled(True)
		self.pushButtonHelicopterForward.setMinimumSize(QtCore.QSize(0, 0))
		self.pushButtonHelicopterForward.setMaximumSize(QtCore.QSize(64, 64))
		self.pushButtonHelicopterForward.setText("")
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap("images/orbit-fly_forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.pushButtonHelicopterForward.setIcon(icon2)
		self.pushButtonHelicopterForward.setIconSize(QtCore.QSize(50, 50))
		self.pushButtonHelicopterForward.setCheckable(True)
		self.pushButtonHelicopterForward.setObjectName("pushButtonHelicopterForward")
		self.gridLayoutFlightPlan.addWidget(self.pushButtonHelicopterForward, 2, 1, 1, 1)
		self.labelHelicopterHover_2 = QtGui.QLabel(self.horizontalLayoutWidget)
		self.labelHelicopterHover_2.setMidLineWidth(0)
		self.labelHelicopterHover_2.setTextFormat(QtCore.Qt.AutoText)
		self.labelHelicopterHover_2.setAlignment(QtCore.Qt.AlignCenter)
		self.labelHelicopterHover_2.setObjectName("labelHelicopterHover_2")
		self.gridLayoutFlightPlan.addWidget(self.labelHelicopterHover_2, 3, 0, 1, 1)
		self.labelHelicopterHover_3 = QtGui.QLabel(self.horizontalLayoutWidget)
		self.labelHelicopterHover_3.setMidLineWidth(0)
		self.labelHelicopterHover_3.setTextFormat(QtCore.Qt.AutoText)
		self.labelHelicopterHover_3.setAlignment(QtCore.Qt.AlignCenter)
		self.labelHelicopterHover_3.setObjectName("labelHelicopterHover_3")
		self.gridLayoutFlightPlan.addWidget(self.labelHelicopterHover_3, 3, 1, 1, 1)
		self.labelHelicopterHover_4 = QtGui.QLabel(self.horizontalLayoutWidget)
		self.labelHelicopterHover_4.setMidLineWidth(0)
		self.labelHelicopterHover_4.setTextFormat(QtCore.Qt.AutoText)
		self.labelHelicopterHover_4.setAlignment(QtCore.Qt.AlignCenter)
		self.labelHelicopterHover_4.setObjectName("labelHelicopterHover_4")
		self.gridLayoutFlightPlan.addWidget(self.labelHelicopterHover_4, 3, 2, 1, 1)
		self.pushButtonHelicopterLand = QtGui.QPushButton(self.horizontalLayoutWidget)
		self.pushButtonHelicopterLand.setEnabled(True)
		self.pushButtonHelicopterLand.setMinimumSize(QtCore.QSize(0, 0))
		self.pushButtonHelicopterLand.setMaximumSize(QtCore.QSize(64, 64))
		self.pushButtonHelicopterLand.setText("")
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap("images/orbit-land_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.pushButtonHelicopterLand.setIcon(icon3)
		self.pushButtonHelicopterLand.setIconSize(QtCore.QSize(50, 50))
		self.pushButtonHelicopterLand.setCheckable(False)
		self.pushButtonHelicopterLand.setObjectName("pushButtonHelicopterLand")
		self.gridLayoutFlightPlan.addWidget(self.pushButtonHelicopterLand, 4, 2, 1, 1)
		self.pushButtonHelicopterSpinRight = QtGui.QPushButton(self.horizontalLayoutWidget)
		self.pushButtonHelicopterSpinRight.setEnabled(True)
		self.pushButtonHelicopterSpinRight.setMinimumSize(QtCore.QSize(0, 0))
		self.pushButtonHelicopterSpinRight.setMaximumSize(QtCore.QSize(64, 64))
		self.pushButtonHelicopterSpinRight.setText("")
		icon4 = QtGui.QIcon()
		icon4.addPixmap(QtGui.QPixmap("images/orbit-rudder-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.pushButtonHelicopterSpinRight.setIcon(icon4)
		self.pushButtonHelicopterSpinRight.setIconSize(QtCore.QSize(40, 40))
		self.pushButtonHelicopterSpinRight.setCheckable(True)
		self.pushButtonHelicopterSpinRight.setChecked(False)
		self.pushButtonHelicopterSpinRight.setObjectName("pushButtonHelicopterSpinRight")
		self.gridLayoutFlightPlan.addWidget(self.pushButtonHelicopterSpinRight, 4, 1, 1, 1)
		self.pushButtonHelicopterTestFly = QtGui.QPushButton(self.horizontalLayoutWidget)
		self.pushButtonHelicopterTestFly.setEnabled(True)
		self.pushButtonHelicopterTestFly.setMinimumSize(QtCore.QSize(0, 0))
		self.pushButtonHelicopterTestFly.setMaximumSize(QtCore.QSize(64, 64))
		self.pushButtonHelicopterTestFly.setText("")
		icon5 = QtGui.QIcon()
		icon5.addPixmap(QtGui.QPixmap("images/orbit_helicopter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.pushButtonHelicopterTestFly.setIcon(icon5)
		self.pushButtonHelicopterTestFly.setIconSize(QtCore.QSize(40, 40))
		self.pushButtonHelicopterTestFly.setCheckable(False)
		self.pushButtonHelicopterTestFly.setChecked(False)
		self.pushButtonHelicopterTestFly.setObjectName("pushButtonHelicopterTestFly")
		self.gridLayoutFlightPlan.addWidget(self.pushButtonHelicopterTestFly, 2, 2, 1, 1)
		self.verticalLayoutFlightPlan.addLayout(self.gridLayoutFlightPlan)
		spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayoutFlightPlan.addItem(spacerItem6)
		self.horizontalLayoutFlightPlan.addLayout(self.verticalLayoutFlightPlan)
		self.verticalLayoutThrottleYawPitch = QtGui.QVBoxLayout()
		self.verticalLayoutThrottleYawPitch.setObjectName("verticalLayoutThrottleYawPitch")
		self.horizontalLayoutOrbitThrottle = QtGui.QHBoxLayout()
		self.horizontalLayoutOrbitThrottle.setObjectName("horizontalLayoutOrbitThrottle")
		spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutOrbitThrottle.addItem(spacerItem7)
		self.labelOrbitThrottle = QtGui.QLabel(self.horizontalLayoutWidget)
		self.labelOrbitThrottle.setTextFormat(QtCore.Qt.PlainText)
		self.labelOrbitThrottle.setObjectName("labelOrbitThrottle")
		self.horizontalLayoutOrbitThrottle.addWidget(self.labelOrbitThrottle)
		spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutOrbitThrottle.addItem(spacerItem8)
		self.verticalLayoutThrottleYawPitch.addLayout(self.horizontalLayoutOrbitThrottle)
		self.horizontalSliderOrbitThrottle = QtGui.QSlider(self.horizontalLayoutWidget)
		self.horizontalSliderOrbitThrottle.setEnabled(True)
		self.horizontalSliderOrbitThrottle.setMaximum(127)
		self.horizontalSliderOrbitThrottle.setPageStep(2)
		self.horizontalSliderOrbitThrottle.setProperty("value", 80)
		self.horizontalSliderOrbitThrottle.setSliderPosition(80)
		self.horizontalSliderOrbitThrottle.setTracking(True)
		self.horizontalSliderOrbitThrottle.setOrientation(QtCore.Qt.Horizontal)
		self.horizontalSliderOrbitThrottle.setInvertedAppearance(False)
		self.horizontalSliderOrbitThrottle.setInvertedControls(False)
		self.horizontalSliderOrbitThrottle.setTickPosition(QtGui.QSlider.TicksAbove)
		self.horizontalSliderOrbitThrottle.setTickInterval(10)
		self.horizontalSliderOrbitThrottle.setObjectName("horizontalSliderOrbitThrottle")
		self.verticalLayoutThrottleYawPitch.addWidget(self.horizontalSliderOrbitThrottle)
		self.horizontalLayoutOrbitYaw = QtGui.QHBoxLayout()
		self.horizontalLayoutOrbitYaw.setObjectName("horizontalLayoutOrbitYaw")
		spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutOrbitYaw.addItem(spacerItem9)
		self.labelOrbitYaw = QtGui.QLabel(self.horizontalLayoutWidget)
		self.labelOrbitYaw.setTextFormat(QtCore.Qt.PlainText)
		self.labelOrbitYaw.setObjectName("labelOrbitYaw")
		self.horizontalLayoutOrbitYaw.addWidget(self.labelOrbitYaw)
		spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutOrbitYaw.addItem(spacerItem10)
		self.verticalLayoutThrottleYawPitch.addLayout(self.horizontalLayoutOrbitYaw)
		self.horizontalSliderOrbitYaw = QtGui.QSlider(self.horizontalLayoutWidget)
		self.horizontalSliderOrbitYaw.setEnabled(True)
		self.horizontalSliderOrbitYaw.setMaximum(127)
		self.horizontalSliderOrbitYaw.setPageStep(2)
		self.horizontalSliderOrbitYaw.setProperty("value", 78)
		self.horizontalSliderOrbitYaw.setSliderPosition(78)
		self.horizontalSliderOrbitYaw.setTracking(True)
		self.horizontalSliderOrbitYaw.setOrientation(QtCore.Qt.Horizontal)
		self.horizontalSliderOrbitYaw.setInvertedAppearance(False)
		self.horizontalSliderOrbitYaw.setInvertedControls(False)
		self.horizontalSliderOrbitYaw.setTickPosition(QtGui.QSlider.TicksAbove)
		self.horizontalSliderOrbitYaw.setTickInterval(10)
		self.horizontalSliderOrbitYaw.setObjectName("horizontalSliderOrbitYaw")
		self.verticalLayoutThrottleYawPitch.addWidget(self.horizontalSliderOrbitYaw)
		self.horizontalLayoutOrbitPitch = QtGui.QHBoxLayout()
		self.horizontalLayoutOrbitPitch.setObjectName("horizontalLayoutOrbitPitch")
		spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutOrbitPitch.addItem(spacerItem11)
		self.labelOrbitPitch = QtGui.QLabel(self.horizontalLayoutWidget)
		self.labelOrbitPitch.setTextFormat(QtCore.Qt.PlainText)
		self.labelOrbitPitch.setObjectName("labelOrbitPitch")
		self.horizontalLayoutOrbitPitch.addWidget(self.labelOrbitPitch)
		spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayoutOrbitPitch.addItem(spacerItem12)
		self.verticalLayoutThrottleYawPitch.addLayout(self.horizontalLayoutOrbitPitch)
		self.horizontalSliderOrbitPitch = QtGui.QSlider(self.horizontalLayoutWidget)
		self.horizontalSliderOrbitPitch.setEnabled(True)
		self.horizontalSliderOrbitPitch.setMaximum(63)
		self.horizontalSliderOrbitPitch.setPageStep(2)
		self.horizontalSliderOrbitPitch.setProperty("value", 31)
		self.horizontalSliderOrbitPitch.setSliderPosition(31)
		self.horizontalSliderOrbitPitch.setTracking(True)
		self.horizontalSliderOrbitPitch.setOrientation(QtCore.Qt.Horizontal)
		self.horizontalSliderOrbitPitch.setInvertedAppearance(False)
		self.horizontalSliderOrbitPitch.setInvertedControls(False)
		self.horizontalSliderOrbitPitch.setTickPosition(QtGui.QSlider.TicksAbove)
		self.horizontalSliderOrbitPitch.setTickInterval(10)
		self.horizontalSliderOrbitPitch.setObjectName("horizontalSliderOrbitPitch")
		self.verticalLayoutThrottleYawPitch.addWidget(self.horizontalSliderOrbitPitch)
		spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayoutThrottleYawPitch.addItem(spacerItem13)
		self.horizontalLayoutFlightPlan.addLayout(self.verticalLayoutThrottleYawPitch)
		self.verticalLayout_4.addLayout(self.horizontalLayoutFlightPlan)
		self.horizontalLayout_6 = QtGui.QHBoxLayout()
		self.horizontalLayout_6.setObjectName("horizontalLayout_6")
		spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_6.addItem(spacerItem14)
		self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget)
		self.label_6.setTextFormat(QtCore.Qt.AutoText)
		self.label_6.setObjectName("label_6")
		self.horizontalLayout_6.addWidget(self.label_6)
		spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_6.addItem(spacerItem15)
		self.verticalLayout_4.addLayout(self.horizontalLayout_6)
		self.widgetPlotHistory = QtGui.QWidget(self.horizontalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.widgetPlotHistory.sizePolicy().hasHeightForWidth())
		self.widgetPlotHistory.setSizePolicy(sizePolicy)
		self.widgetPlotHistory.setMinimumSize(QtCore.QSize(520, 160))
		self.widgetPlotHistory.setObjectName("widgetPlotHistory")
		self.labelMockupHistory = QtGui.QLabel(self.widgetPlotHistory)
		self.labelMockupHistory.setGeometry(QtCore.QRect(0, 0, 520, 160))
		self.labelMockupHistory.setText("")
		self.labelMockupHistory.setPixmap(QtGui.QPixmap("images/mockup-esense_values_history.jpg"))
		self.labelMockupHistory.setScaledContents(True)
		self.labelMockupHistory.setObjectName("labelMockupHistory")
		self.verticalLayout_4.addWidget(self.widgetPlotHistory)
		spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayout_4.addItem(spacerItem16)
		self.horizontalLayout.addLayout(self.verticalLayout_4)
		spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem17)
		self.verticalLayoutSessionProfile = QtGui.QVBoxLayout()
		self.verticalLayoutSessionProfile.setObjectName("verticalLayoutSessionProfile")
		spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayoutSessionProfile.addItem(spacerItem18)
		self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget)
		self.label_2.setObjectName("label_2")
		self.verticalLayoutSessionProfile.addWidget(self.label_2)
		self.horizontalLayout_8 = QtGui.QHBoxLayout()
		self.horizontalLayout_8.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
		self.horizontalLayout_8.setObjectName("horizontalLayout_8")
		self.textLabelOrbitConcentration = QtGui.QLabel(self.horizontalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.textLabelOrbitConcentration.sizePolicy().hasHeightForWidth())
		self.textLabelOrbitConcentration.setSizePolicy(sizePolicy)
		self.textLabelOrbitConcentration.setWordWrap(False)
		self.textLabelOrbitConcentration.setObjectName("textLabelOrbitConcentration")
		self.horizontalLayout_8.addWidget(self.textLabelOrbitConcentration)
		spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_8.addItem(spacerItem19)
		self.pushButtonOrbitConcentrationEnable = QtGui.QPushButton(self.horizontalLayoutWidget)
		self.pushButtonOrbitConcentrationEnable.setEnabled(False)
		self.pushButtonOrbitConcentrationEnable.setCheckable(True)
		self.pushButtonOrbitConcentrationEnable.setChecked(True)
		self.pushButtonOrbitConcentrationEnable.setObjectName("pushButtonOrbitConcentrationEnable")
		self.horizontalLayout_8.addWidget(self.pushButtonOrbitConcentrationEnable)
		self.verticalLayoutSessionProfile.addLayout(self.horizontalLayout_8)
		self.progressBarOrbitConcentration = QtGui.QProgressBar(self.horizontalLayoutWidget)
		self.progressBarOrbitConcentration.setEnabled(True)
		self.progressBarOrbitConcentration.setMinimumSize(QtCore.QSize(0, 60))
		self.progressBarOrbitConcentration.setProperty("value", 0)
		self.progressBarOrbitConcentration.setOrientation(QtCore.Qt.Horizontal)
		self.progressBarOrbitConcentration.setObjectName("progressBarOrbitConcentration")
		self.verticalLayoutSessionProfile.addWidget(self.progressBarOrbitConcentration)
		self.horizontalSliderOrbitConcentration = QtGui.QSlider(self.horizontalLayoutWidget)
		self.horizontalSliderOrbitConcentration.setEnabled(True)
		self.horizontalSliderOrbitConcentration.setMaximum(100)
		self.horizontalSliderOrbitConcentration.setPageStep(2)
		self.horizontalSliderOrbitConcentration.setProperty("value", 72)
		self.horizontalSliderOrbitConcentration.setSliderPosition(72)
		self.horizontalSliderOrbitConcentration.setTracking(True)
		self.horizontalSliderOrbitConcentration.setOrientation(QtCore.Qt.Horizontal)
		self.horizontalSliderOrbitConcentration.setInvertedAppearance(False)
		self.horizontalSliderOrbitConcentration.setInvertedControls(False)
		self.horizontalSliderOrbitConcentration.setTickPosition(QtGui.QSlider.TicksAbove)
		self.horizontalSliderOrbitConcentration.setTickInterval(10)
		self.horizontalSliderOrbitConcentration.setObjectName("horizontalSliderOrbitConcentration")
		self.verticalLayoutSessionProfile.addWidget(self.horizontalSliderOrbitConcentration)
		self.horizontalLayout_9 = QtGui.QHBoxLayout()
		self.horizontalLayout_9.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
		self.horizontalLayout_9.setObjectName("horizontalLayout_9")
		self.textLabelOrbitRelaxation = QtGui.QLabel(self.horizontalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.textLabelOrbitRelaxation.sizePolicy().hasHeightForWidth())
		self.textLabelOrbitRelaxation.setSizePolicy(sizePolicy)
		self.textLabelOrbitRelaxation.setWordWrap(False)
		self.textLabelOrbitRelaxation.setObjectName("textLabelOrbitRelaxation")
		self.horizontalLayout_9.addWidget(self.textLabelOrbitRelaxation)
		spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_9.addItem(spacerItem20)
		self.pushButtonOrbitRelaxationEnable = QtGui.QPushButton(self.horizontalLayoutWidget)
		self.pushButtonOrbitRelaxationEnable.setEnabled(False)
		self.pushButtonOrbitRelaxationEnable.setCheckable(True)
		self.pushButtonOrbitRelaxationEnable.setChecked(True)
		self.pushButtonOrbitRelaxationEnable.setObjectName("pushButtonOrbitRelaxationEnable")
		self.horizontalLayout_9.addWidget(self.pushButtonOrbitRelaxationEnable)
		self.verticalLayoutSessionProfile.addLayout(self.horizontalLayout_9)
		self.progressBarOrbitRelaxation = QtGui.QProgressBar(self.horizontalLayoutWidget)
		self.progressBarOrbitRelaxation.setEnabled(True)
		self.progressBarOrbitRelaxation.setMinimumSize(QtCore.QSize(0, 60))
		self.progressBarOrbitRelaxation.setProperty("value", 0)
		self.progressBarOrbitRelaxation.setOrientation(QtCore.Qt.Horizontal)
		self.progressBarOrbitRelaxation.setObjectName("progressBarOrbitRelaxation")
		self.verticalLayoutSessionProfile.addWidget(self.progressBarOrbitRelaxation)
		self.horizontalSliderOrbitRelaxation = QtGui.QSlider(self.horizontalLayoutWidget)
		self.horizontalSliderOrbitRelaxation.setEnabled(True)
		self.horizontalSliderOrbitRelaxation.setMaximum(100)
		self.horizontalSliderOrbitRelaxation.setPageStep(2)
		self.horizontalSliderOrbitRelaxation.setProperty("value", 0)
		self.horizontalSliderOrbitRelaxation.setSliderPosition(0)
		self.horizontalSliderOrbitRelaxation.setTracking(True)
		self.horizontalSliderOrbitRelaxation.setOrientation(QtCore.Qt.Horizontal)
		self.horizontalSliderOrbitRelaxation.setInvertedAppearance(False)
		self.horizontalSliderOrbitRelaxation.setInvertedControls(False)
		self.horizontalSliderOrbitRelaxation.setTickPosition(QtGui.QSlider.TicksAbove)
		self.horizontalSliderOrbitRelaxation.setTickInterval(10)
		self.horizontalSliderOrbitRelaxation.setObjectName("horizontalSliderOrbitRelaxation")
		self.verticalLayoutSessionProfile.addWidget(self.horizontalSliderOrbitRelaxation)
		self.horizontalLayout_10 = QtGui.QHBoxLayout()
		self.horizontalLayout_10.setObjectName("horizontalLayout_10")
		self.textLabelOrbitConnectionLevel = QtGui.QLabel(self.horizontalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.textLabelOrbitConnectionLevel.sizePolicy().hasHeightForWidth())
		self.textLabelOrbitConnectionLevel.setSizePolicy(sizePolicy)
		self.textLabelOrbitConnectionLevel.setWordWrap(False)
		self.textLabelOrbitConnectionLevel.setObjectName("textLabelOrbitConnectionLevel")
		self.horizontalLayout_10.addWidget(self.textLabelOrbitConnectionLevel)
		spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_10.addItem(spacerItem21)
		self.verticalLayoutSessionProfile.addLayout(self.horizontalLayout_10)
		self.progressBarOrbitConnectionLevel = QtGui.QProgressBar(self.horizontalLayoutWidget)
		self.progressBarOrbitConnectionLevel.setEnabled(True)
		self.progressBarOrbitConnectionLevel.setProperty("value", 0)
		self.progressBarOrbitConnectionLevel.setOrientation(QtCore.Qt.Horizontal)
		self.progressBarOrbitConnectionLevel.setObjectName("progressBarOrbitConnectionLevel")
		self.verticalLayoutSessionProfile.addWidget(self.progressBarOrbitConnectionLevel)
		self.horizontalLayout_11 = QtGui.QHBoxLayout()
		self.horizontalLayout_11.setObjectName("horizontalLayout_11")
		self.textLabelOrbitConnectionLevel_2 = QtGui.QLabel(self.horizontalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.textLabelOrbitConnectionLevel_2.sizePolicy().hasHeightForWidth())
		self.textLabelOrbitConnectionLevel_2.setSizePolicy(sizePolicy)
		self.textLabelOrbitConnectionLevel_2.setWordWrap(False)
		self.textLabelOrbitConnectionLevel_2.setObjectName("textLabelOrbitConnectionLevel_2")
		self.horizontalLayout_11.addWidget(self.textLabelOrbitConnectionLevel_2)
		spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_11.addItem(spacerItem22)
		self.verticalLayoutSessionProfile.addLayout(self.horizontalLayout_11)
		self.progressBarOrbitPower = QtGui.QProgressBar(self.horizontalLayoutWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.progressBarOrbitPower.sizePolicy().hasHeightForWidth())
		self.progressBarOrbitPower.setSizePolicy(sizePolicy)
		self.progressBarOrbitPower.setMinimumSize(QtCore.QSize(100, 0))
		self.progressBarOrbitPower.setProperty("value", 65)
		self.progressBarOrbitPower.setOrientation(QtCore.Qt.Horizontal)
		self.progressBarOrbitPower.setObjectName("progressBarOrbitPower")
		self.verticalLayoutSessionProfile.addWidget(self.progressBarOrbitPower)
		spacerItem23 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayoutSessionProfile.addItem(spacerItem23)
		self.labelInfraredControlModule = QtGui.QLabel(self.horizontalLayoutWidget)
		self.labelInfraredControlModule.setEnabled(True)
		self.labelInfraredControlModule.setAlignment(QtCore.Qt.AlignCenter)
		self.labelInfraredControlModule.setObjectName("labelInfraredControlModule")
		self.verticalLayoutSessionProfile.addWidget(self.labelInfraredControlModule)
		self.textLabelInfraredStatus = QtGui.QLabel(self.horizontalLayoutWidget)
		self.textLabelInfraredStatus.setEnabled(True)
		self.textLabelInfraredStatus.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelInfraredStatus.setWordWrap(False)
		self.textLabelInfraredStatus.setObjectName("textLabelInfraredStatus")
		self.verticalLayoutSessionProfile.addWidget(self.textLabelInfraredStatus)
		self.textLabelInfraredHardwareSelection = QtGui.QLabel(self.horizontalLayoutWidget)
		self.textLabelInfraredHardwareSelection.setEnabled(True)
		self.textLabelInfraredHardwareSelection.setAlignment(QtCore.Qt.AlignCenter)
		self.textLabelInfraredHardwareSelection.setWordWrap(False)
		self.textLabelInfraredHardwareSelection.setObjectName("textLabelInfraredHardwareSelection")
		self.verticalLayoutSessionProfile.addWidget(self.textLabelInfraredHardwareSelection)
		self.comboBoxInfraredModelName = QtGui.QComboBox(self.horizontalLayoutWidget)
		self.comboBoxInfraredModelName.setEnabled(True)
		self.comboBoxInfraredModelName.setObjectName("comboBoxInfraredModelName")
		self.comboBoxInfraredModelName.addItem("")
		self.comboBoxInfraredModelName.addItem("")
		self.comboBoxInfraredModelName.addItem("")
		self.comboBoxInfraredModelName.addItem("")
		self.verticalLayoutSessionProfile.addWidget(self.comboBoxInfraredModelName)
		self.comboBoxInfraredPortSelect = QtGui.QComboBox(self.horizontalLayoutWidget)
		self.comboBoxInfraredPortSelect.setEnabled(True)
		self.comboBoxInfraredPortSelect.setObjectName("comboBoxInfraredPortSelect")
		self.comboBoxInfraredPortSelect.addItem("")
		self.verticalLayoutSessionProfile.addWidget(self.comboBoxInfraredPortSelect)
		self.horizontalLayoutSessionButtons_2 = QtGui.QHBoxLayout()
		self.horizontalLayoutSessionButtons_2.setObjectName("horizontalLayoutSessionButtons_2")
		self.pushButtonInfraredConnect = QtGui.QPushButton(self.horizontalLayoutWidget)
		self.pushButtonInfraredConnect.setEnabled(True)
		self.pushButtonInfraredConnect.setCheckable(True)
		self.pushButtonInfraredConnect.setObjectName("pushButtonInfraredConnect")
		self.horizontalLayoutSessionButtons_2.addWidget(self.pushButtonInfraredConnect)
		self.pushButtonInfraredSearch = QtGui.QPushButton(self.horizontalLayoutWidget)
		self.pushButtonInfraredSearch.setCheckable(False)
		self.pushButtonInfraredSearch.setObjectName("pushButtonInfraredSearch")
		self.horizontalLayoutSessionButtons_2.addWidget(self.pushButtonInfraredSearch)
		self.verticalLayoutSessionProfile.addLayout(self.horizontalLayoutSessionButtons_2)
		spacerItem24 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayoutSessionProfile.addItem(spacerItem24)
		self.horizontalLayout.addLayout(self.verticalLayoutSessionProfile)
		spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem25)

		self.retranslateUi(Form)
		QtCore.QMetaObject.connectSlotsByName(Form)

	def retranslateUi(self, Form):
		Form.setWindowTitle(QtGui.QApplication.translate("Form", "Puzzlebox Jigsaw - Plug-in - Orbit", None, QtGui.QApplication.UnicodeUTF8))
		self.label_4.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Raw EEG Waves</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.labelOrbitControl.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Flight Plan\n"
"</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.labelHelicopterLand.setText(QtGui.QApplication.translate("Form", "Test Fly", None, QtGui.QApplication.UnicodeUTF8))
		self.labelHelicopterHover.setText(QtGui.QApplication.translate("Form", "Hover", None, QtGui.QApplication.UnicodeUTF8))
		self.labelHelicopterFlyForward.setText(QtGui.QApplication.translate("Form", "Forward", None, QtGui.QApplication.UnicodeUTF8))
		self.labelHelicopterHover_2.setText(QtGui.QApplication.translate("Form", "Spin Left", None, QtGui.QApplication.UnicodeUTF8))
		self.labelHelicopterHover_3.setText(QtGui.QApplication.translate("Form", "Spin Right", None, QtGui.QApplication.UnicodeUTF8))
		self.labelHelicopterHover_4.setText(QtGui.QApplication.translate("Form", "Land", None, QtGui.QApplication.UnicodeUTF8))
		self.labelOrbitThrottle.setText(QtGui.QApplication.translate("Form", "Throttle", None, QtGui.QApplication.UnicodeUTF8))
		self.labelOrbitYaw.setText(QtGui.QApplication.translate("Form", "Yaw", None, QtGui.QApplication.UnicodeUTF8))
		self.labelOrbitPitch.setText(QtGui.QApplication.translate("Form", "Pitch", None, QtGui.QApplication.UnicodeUTF8))
		self.label_6.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Brain Signals History</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.label_2.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans\'; font-size:10pt; font-weight:600;\">Current Data</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelOrbitConcentration.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Concentration</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonOrbitConcentrationEnable.setToolTip(QtGui.QApplication.translate("Form", "enable/disable concentration processing", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonOrbitConcentrationEnable.setText(QtGui.QApplication.translate("Form", "Enabled", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelOrbitRelaxation.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Relaxation</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonOrbitRelaxationEnable.setToolTip(QtGui.QApplication.translate("Form", "enable/disable relaxation processing", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonOrbitRelaxationEnable.setText(QtGui.QApplication.translate("Form", "Enabled", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelOrbitConnectionLevel.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ground/Reference Signal</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelOrbitConnectionLevel_2.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Orbit Power Level</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.labelInfraredControlModule.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Orbit Control Module</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelInfraredStatus.setText(QtGui.QApplication.translate("Form", "<p align=\"center\">Status: Disconnected</p>", None, QtGui.QApplication.UnicodeUTF8))
		self.textLabelInfraredHardwareSelection.setText(QtGui.QApplication.translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Hardware Selection</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
		self.comboBoxInfraredModelName.setItemText(0, QtGui.QApplication.translate("Form", "Puzzlebox Bloom", None, QtGui.QApplication.UnicodeUTF8))
		self.comboBoxInfraredModelName.setItemText(1, QtGui.QApplication.translate("Form", "Puzzlebox Pyramid", None, QtGui.QApplication.UnicodeUTF8))
		self.comboBoxInfraredModelName.setItemText(2, QtGui.QApplication.translate("Form", "Audio Infrared Dongle", None, QtGui.QApplication.UnicodeUTF8))
		self.comboBoxInfraredModelName.setItemText(3, QtGui.QApplication.translate("Form", "Arduino Infrared Circuit", None, QtGui.QApplication.UnicodeUTF8))
		self.comboBoxInfraredPortSelect.setItemText(0, QtGui.QApplication.translate("Form", "Select Port", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonInfraredConnect.setText(QtGui.QApplication.translate("Form", "Connect", None, QtGui.QApplication.UnicodeUTF8))
		self.pushButtonInfraredSearch.setText(QtGui.QApplication.translate("Form", "Search", None, QtGui.QApplication.UnicodeUTF8))

from PySide import QtWebKit
